### ISSUE TITLE
'Register' New User Function Broken after Heroic.IOC install

### ISSUE THREAD

**Issue by RobertBonham** [MattHoneycutt/HeroicFramework#1]
When selecting 'Register' to register a new local account in my Asp.net MVC app, I receive the following error screen. 

No default Instance is registered and cannot be automatically determined for type 'IUserStore<ApplicationUser>'

There is no configuration specified for IUserStore<ApplicationUser>

1.) new ApplicationUserManager(_Default of IUserStore<ApplicationUser>_)
2.) MvcHeroic.ApplicationUserManager
3.) Instance of MvcHeroic.ApplicationUserManager
4.) new AccountController(_Default of ApplicationUserManager_, _Default of ApplicationSignInManager_)
5.) MvcHeroic.Controllers.AccountController
6.) Instance of MvcHeroic.Controllers.AccountController
7.) Container.GetInstance(MvcHeroic.Controllers.AccountController)

Note:  I'm not sure if HeroicFramework.IOC is supposed to work 'out of the box' with the default mvc project registration, or if I'm expected to follow a pattern like FailTracker uses.

**Comment by RobertBonham** [comment]
Hey Matt, I'm new to trying to contribute to GitHub, so I'm not sure how to try to contribute to solve my own problem on this.  I cloned the HeroicFramework to my desktop (using GitHub for windows) and added the following code (from another of your projects) to StructureMapConfig.cs.pp, but couldn't manage to perform a 'pull request' which is what I think I'm supposed to do.  Regardless of if you want the code in the project, would that have been the correct steps?  Does a person normally need to be added to a project first to attempt to contribute? Is there a way to contribute without being a member?  Thanks Matt

// If using Asp.net MVC Local Accounts  
//  cfg.For<ApplicationSignInManager>().Use(ctx =>
//    ctx.GetInstance<HttpContextBase>().GetOwinContext().Get<ApplicationSignInManager>());
//  cfg.For<ApplicationUserManager>().Use(ctx =>
//    ctx.GetInstance<HttpContextBase>().GetOwinContext().GetUserManager<ApplicationUserManager>());
//TODO: Add other registries and configure your container!

**Comment by MattHoneycutt** [comment]
Sorry I haven't gotten back to you yet.  I know what's going on, I just have to type up instructions on how to fix it, and possibly even add something to the package to fix it for you when it detects that you are using ASP.NET Identity. :)

**Comment by RobertBonham** [comment]
Excellent, thanks for all your great work Matt.

**Comment by MattHoneycutt** [comment]
I apologize for the delay.  I was trying to find an automated solution to this, but so far, I haven't been able to find one.  I might make another NuGet package to assist.

In the meantime, what you'll need to do is add the following code to your StructureMapConfig file.  You can drop it in where there's already a //TODO: 

```
//1) Make IUserStore injectable.  Replace 'ApplicationUser' with whatever your Identity user type is.
For<IUserStore<ApplicationUser>>().Use<UserStore<ApplicationUser>>();

//2) Change AppDbContext to your application's Entity Framework context.
For<DbContext>().Use<AppDbContext>();

//3) This will allow you to inject the IAuthenticationManager.  You may not need this, but you will if you 
//   used the default ASP.NET MVC project template as a starting point!
For<IAuthenticationManager>().Use(ctx => ctx.GetInstance<HttpRequestBase>().GetOwinContext().Authentication);
```

You may need to import some namespaces and change types to match your application.  

Please let me know if that takes care of your issue.
