### ISSUE TITLE
What does the PreDisposeContainer Action do?

### ISSUE THREAD

**Issue by ChuckBryan** [MattHoneycutt/HeroicFramework#11]
I was looking through the code and saw the PreDisposeContainer Action. I see the comment that the definition ensures the event is always fired, but, what is it actually delegating to?

**Comment by MattHoneycutt** [comment]
@ChuckBryan It's called at the end of a request, but *before* the container has actually been disposed of.  You can use this hook if you need last-minute access services in the request's nested container before that container is disposed of.

**Comment by ChuckBryan** [comment]
Thanks Matt!
