### ISSUE TITLE
Running Tasks

### ISSUE THREAD

**Issue by saomcol** [MattHoneycutt/HeroicFramework#2]
Learning the ropes. After your framework course, I've been trying to incorporate tasks into the Heroic Ioc but couldn't figure out how to get the container in the global asax. IRunAtStartup tasks run but the others doesn't, failing with run time null reference for container. Any pointers?

**Comment by MattHoneycutt** [comment]
The StructureMapContainerPerRequestModule.Container helper property will give you access to the nested container for the current request.  

This may help, too.  It shows how Fail Tracker grabs the container in global.asax via Heroic.IoC: https://github.com/MattHoneycutt/Fail-Tracker/blob/heroic-framework/FailTracker.Web/Global.asax.cs

Let me know if that helps!

**Comment by saomcol** [comment]
Thanks a lot. this worked.
