### ISSUE TITLE
Missing Map Error Heroic Automapper

### ISSUE THREAD

**Issue by saomcol** [MattHoneycutt/HeroicFramework#3]
Using the static automapperconfig class, I get this error after compiling and publishing the site:
_Missing map from ApplicationUser to IndexViewModel. Create using Mapper.CreateMap<ApplicationUser, IndexViewModel>._

It works fine when I change it like this:

``` C#
using Heroic.AutoMapper;
using SDPManager.Infrastructure.Tasks;

//[assembly: WebActivatorEx.PreApplicationStartMethod(typeof(SDPManager.AutoMapperConfig), "Configure")]

namespace SDPManager
{
    public class AutoMapperConfig : IRunAtInit
    {
        public static void Configure()
        {
            //NOTE: By default, the current project and all referenced projects will be scanned.
            //      You can customize this by passing in a lambda to filter the assemblies by name,
            //      like so:
            //HeroicAutoMapperConfigurator.LoadMapsFromCallerAndReferencedAssemblies(x => x.Name.StartsWith("SDPManager"));
            HeroicAutoMapperConfigurator.LoadMapsFromCallerAndReferencedAssemblies();
        }

        public void Execute()
        {
            HeroicAutoMapperConfigurator.LoadMapsFromCallerAndReferencedAssemblies(x => x.Name.StartsWith("SDPManager"));
        }
    }
}

```

**Comment by MattHoneycutt** [comment]
Hmm, where is that error being thrown from?  If it is happening in code
that's executing during your applications initialization, it's possible
that the code is running before WebActivator runs.  If it's running
somewhere else, then it would appear that WebActivator isn't executing...
Please let me know which it is, so I can investigate further.  Thanks!
