### ISSUE TITLE
Update to Structuremap 4

### ISSUE THREAD

**Issue by saomcol** [MattHoneycutt/HeroicFramework#4]
Just noticed breaking changes when I updated to structuremap 4.0

**Comment by MattHoneycutt** [comment]
Yup, I'm going to tackle this ASAP.

**Comment by MattHoneycutt** [comment]
Upgrade to SM 4.0 is complete!  Please update to Heroic.Web.IoC version 4.0.0.  Thanks!

**Comment by saomcol** [comment]
Thanks
