### ISSUE TITLE
StructureMapConfig - not recognizing For

### ISSUE THREAD

**Issue by rswetnam** [MattHoneycutt/HeroicFramework#5]
Matt:

I just created a vanilla Asp.Net MVC project from Visual Studio 2015.  I then added Heroic.Web.Ioc via GitHub.  Those are the only two actions I took - made no updates or any other changes.  

When I uncommented line 31 in StructureMapConfig.cs, I get a compiler warning that 'The Name For does not exist in the current context'.  I have posted the project to GitHub at https://github.com/rswetnam/HeroicTest.  Do you get the same error when you load the project?  Am I doing something wrong?

Regards,
Roger

**Comment by MattHoneycutt** [comment]
Whoops, you are totally right, I left out the "cfg." that should have
prefixed that line.  I'll get that fixed in the next version.

**Comment by MattHoneycutt** [comment]
The template is fixed in Heroic.Web.IoC version 4.1.2.  Thanks for pointing out the issue!

**Comment by rswetnam** [comment]
Thanks for the quick response and fix, Matt!

Roger

On Sat, Feb 20, 2016 at 11:24 AM, Matt Honeycutt notifications@github.com
wrote:

> The template is fixed in Heroic.Web.IoC version 4.1.2. Thanks for pointing
> out the issue!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MattHoneycutt/HeroicFramework/issues/5#issuecomment-186668712
> .

## 

Roger Swetnam
p.  604-408-5703
c.  778-848-3118
